# Site settings
baseurl = "http://mhiatt.github.io/"
languageCode = "en-us"
title = "Myles Hiatt"
theme = "hugo-cactus-theme"

contentdir = "content"

publisdir = "public"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "mhiatt"

[params]
	name = "Myles Hiatt"
	description = "Describe your website"
	bio = "Programmer - Life-long Student - Undecided"
	# Enter optionally your twitter account
	twitter = "Your Twitter account"
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	blog = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm here to learn."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    # twitter  = "https://www.twitter.com/"
		linkedin = "https://www.linkedin.com/in/myles-hiatt-5749916b?trk=nav_responsive_tab_profile"
    facebook = "https://www.facebook.com/myles.hiatt"
    githubalt = "https://www.github.com/mhiatt"
    # dribble  = "https://www.dribbble.com/"
